---
abstract: 'Dist::Zilla plugins for AJGB'
author:
  - 'Alex J. G. Burzyński <ajgb@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300016, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-AJGB
requires:
  Dist::Zilla::Plugin::Authority: 0
  Dist::Zilla::Plugin::AutoMetaResources: 0
  Dist::Zilla::Plugin::AutoPrereqs: 0
  Dist::Zilla::Plugin::CheckChangesHasContent: 0
  Dist::Zilla::Plugin::CheckExtraTests: 0
  Dist::Zilla::Plugin::ConfirmRelease: 0
  Dist::Zilla::Plugin::CopyFilesFromBuild: 0
  Dist::Zilla::Plugin::EOLTests: 0
  Dist::Zilla::Plugin::ExecDir: 0
  Dist::Zilla::Plugin::GatherDir: 0
  Dist::Zilla::Plugin::Git::Check: 0
  Dist::Zilla::Plugin::Git::Commit: 0
  Dist::Zilla::Plugin::Git::NextVersion: 0
  Dist::Zilla::Plugin::Git::Push: 0
  Dist::Zilla::Plugin::Git::Tag: 0
  Dist::Zilla::Plugin::InstallGuide: 0
  Dist::Zilla::Plugin::KwaliteeTests: 0
  Dist::Zilla::Plugin::License: 0
  Dist::Zilla::Plugin::MakeMaker: 0
  Dist::Zilla::Plugin::Manifest: 0
  Dist::Zilla::Plugin::ManifestSkip: 0
  Dist::Zilla::Plugin::MetaConfig: 0
  Dist::Zilla::Plugin::MetaJSON: 0
  Dist::Zilla::Plugin::MetaYAML: 0
  Dist::Zilla::Plugin::ModuleBuild: 0
  Dist::Zilla::Plugin::NextRelease: 0
  Dist::Zilla::Plugin::NoTabsTests: 0
  Dist::Zilla::Plugin::PkgVersion: 0
  Dist::Zilla::Plugin::PodCoverageTests: 0
  Dist::Zilla::Plugin::PodSyntaxTests: 0
  Dist::Zilla::Plugin::PodWeaver: 0
  Dist::Zilla::Plugin::PruneCruft: 0
  Dist::Zilla::Plugin::ReadmeFromPod: 0
  Dist::Zilla::Plugin::ShareDir: 0
  Dist::Zilla::Plugin::Test::Compile: 0
  Dist::Zilla::Plugin::Test::Portability: 0
  Dist::Zilla::Plugin::Test::Synopsis: 0
  Dist::Zilla::Plugin::TestRelease: 0
  Dist::Zilla::Plugin::UploadToCPAN: 0
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Moose: 0
  Pod::Weaver::Config::Assembler: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-PluginBundle-AJGB
  homepage: http://search.cpan.org/dist/Dist-Zilla-PluginBundle-AJGB
  repository: git://github.com/ajgb/dist-zilla-pluginbundle-ajgb.git
version: 2.02
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: ExecDir
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: ShareDir
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: GatherDir
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: MetaYAML
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::License
      name: License
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::Manifest
      name: Manifest
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: Test::Compile
      version: 1.112820
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: PodCoverageTests
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: PodSyntaxTests
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: EOLTests
      version: 0.02
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: NoTabsTests
      version: 0.01
    -
      class: Dist::Zilla::Plugin::KwaliteeTests
      name: KwaliteeTests
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::Test::Portability
      name: Test::Portability
      version: 2.0.2
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: PruneCruft
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: ManifestSkip
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: PkgVersion
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::Authority
      name: Authority
      version: 1.006
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: PodWeaver
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::AutoMetaResources
      name: AutoMetaResources
      version: 1.110050
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: MakeMaker
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: ModuleBuild
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: InstallGuide
      version: 1.101461
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: ReadmeFromPod
      version: 0.16
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: Git::NextVersion
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: CopyFilesFromBuild
      version: 0.103510
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: Git::Check
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: CheckChangesHasContent
      version: 0.005
    -
      class: Dist::Zilla::Plugin::CheckExtraTests
      name: CheckExtraTests
      version: 0.005
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: TestRelease
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: ConfirmRelease
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: UploadToCPAN
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: NextRelease
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: Git::Commit
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: Git::Tag
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: Git::Push
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300016
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300016
x_authority: cpan:AJGB
